🔖 목차
1.
2.
3.
4.

<br/>


## 프로그램 오류 
- 프로그램 수행시 치명적 상황이 발생하여 비정상 종료 상황이 발생한 것,
- 프로그램 에러라고도 한다.

<br/>

## 오류의 종류

- 1. 컴파일 에러 : 프로그램의 실행을 막는 소스 상의 문법 에러, 소스 구문을수정하여 해결
- 2. 런타임 에러 : 입력 값이 틀렸거나, 배열의 인덱스 범위를 벗어났거나,계산식의 오류 등 주로 if문 사용으로 에러 처리
- 3. 시스템 에러 : 컴퓨터 오작동으로 인한 에러, 소스 구문으로 해결 불가

<br/>

## 오류 해결방법
- 소스 수정으로 해결 가능한 에러를 예외(Exception)라고 하는데
- 이러한 예외 상황(예측 가능한 에러) 구문을 처리 하는 방법인 예외처리를 통해 해결

<br/>

## 예외 클래스 계층구조
- Exception과 Error 클래스 모두 Object 클래스의 자손이며
- 모든 예외의 최고 조상은 Exception 클래스
- 반드시 예외 처리해야 하는 Checked Exception과 해주지 않아도 되는  Unchecked Exception으로 나뉨

![예외클래스계층구조](https://user-images.githubusercontent.com/126074577/226928201-77e9bf39-0a21-491e-bea6-e36de3ca89e6.png)

<br/>

# 1.  예외처리 종류

- 발생하는 예외에 대해서 처리하지않아도 되는 예외 를소개하겟다.

<br/>

## ArithmeticException

- 수학적으로 계산이 불가능할때 발생하는 Exception

```java
int su = 10;
int su2 = 0;
System.out.println(su/su2);
```

<br/>

## ArrayIndexOutOfBoundsException
- 배열의 인덱스 범위를 초과해서 접근할때 발생하는 예외

```java
int[] intArr = new int[5];
System.out.println(intArr[5]);
```

<br/>
 
##  ClasscastException
- 클래스형 변환을 잘못했을때발생하는 예외

```java
Object o = new String("안녕");
Integer num = (Integer)o;
```

<br/>

## NullpointException
- 참조형변수에 null값이 있을때 접근연산자를 사용하면 발생하는 Exception

```java
String name = null;
name.length();
```

<br/>


## NumberFormatException

- 문자열을 숫자형으로 변환할때 변환불가능한 문자가 있는경우

``java
int su = 10;
su=Integer.parseInt(name);
```

<br/>

## inputMissMatchException
- 입력값의 타입이 일치하지않을때 발생

```java
Scanner sc = new Scanner(System.in);
su = sc.nextInt();
//입력값  abc
```

<br/>

- **RuntimeException이 발생하면 발생하는 순간 프로그램은 종료된다.**

<br/>

# 2. Exception 발생시 해결방법

- 1.try~catch문을 이용해서 직접예외를 처리하기
- 2.throws 예약어를 이용해서 예외처리 위임하기

<br/>


# 3. try~catch

- 먼저 예시부터 보겟다.

```java
int[] intArr = { 1, 2, 3, 4, 5 };
		try {
			int a = intArr[5];
			System.out.println(a);
			// 캐치문 괄호안에 오류내용을적어야한다.
		} catch (ArrayIndexOutOfBoundsException e) {
			// 캐치에 빠지면 이중괄호가 실행이된다.
			System.out.println("인덱스부족해!");
			int[] temp = new int[intArr.length + 5];
			System.arraycopy(intArr, 0, temp, 0, intArr.length);
			intArr = temp;
			int a = intArr[5];
		}
		System.out.println("실행되니?");
```
- 어렵게 생각하지않아도 된다.
- 우리가 많이 쓰던 if문과 비슷하다고 생각하면 쉽게느껴질것이다.
- 방법을 설명하겠다.

  - 먼저 try를 쓰고 안에 로직을 쓴다.
  - 그런후 끝나는 중괄호에 catch를 쓰고 괄호안에 오류내용을 적고 변수를 선언한다.
  - catch중괄호안에는 오류시 출력할 로직을 쓰면된다.
  - 마치 if else 같지않은가?
  - 비슷하다.

- 한가지 더 알려주자면
- 보통 오류가나면 프로그램이 종료되는데
- 오류가발생해서 catch로 빠지면 catch를 출력한후 바로 밑으로 내려가서 다음걸 읽는다.
- 이것이 **try~catch를 쓰는이유다.**

